### ISSUE TITLE
Release 0.8.3 - panic: interface conversion: interface {} is int, not string

### ISSUE THREAD

**Issue by felipe-itoc** [hirosassa/terraform-provider-looker#21]
**Release:** `0.8.3`

**Resources affected:**
- `looker_connection`
- `looker_user_attribute_group_value`

**Description:** 

Following the resolution of issue [#19](https://github.com/hirosassa/terraform-provider-looker/issues/19) we upgraded our provider to `0.8.3` to fix the HTTP 404 while creating new `looker_user` and `looker_group`.

The issue is now fixed but we got a new exception while creating a `looker_connection` and `looker_user_attribute_group_value`.

We confirmed the right types (string or number) are defined for each attribute and resources based on the latest Terraform documentation but we receive the message `panic: interface conversion: interface {} is int, not string` in the Stack trace.

**Terraform response:**

```
│ Error: Plugin did not respond
│
│   with looker_connection.snowflake_connection,
│   on looker_snowflake_connection.tf line 1, in resource "looker_connection" "snowflake_connection":
│    1: resource "looker_connection" "snowflake_connection" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
│
│
│ Error: Plugin did not respond
│
│   with looker_user_attribute_group_value.snowflake_warehouse,
│   on looker_user_group.tf line 29, in resource "looker_user_attribute_group_value" "snowflake_warehouse":
│   29: resource "looker_user_attribute_group_value" "snowflake_warehouse" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

**Stack trace:**

```
Stack trace from the terraform-provider-looker_v0.8.3 plugin:

panic: interface conversion: interface {} is int, not string

goroutine 82 [running]:
github.com/hirosassa/terraform-provider-looker/pkg/looker.resourceUserAttributeGroupValueCreate({0x1053c8108, 0x1400007cea0}, 0x1400062ad00, {0x1053a3960, 0x14000096338})
	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_user_attribute_group_value.go:41 +0x464
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140002990a0, {0x1053c8140, 0x1400027d110}, 0x1400062ad00, {0x1053a3960, 0x14000096338})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140002990a0, {0x1053c8140, 0x1400027d110}, 0x140003fb110, 0x1400062ab80, {0x1053a3960, 0x14000096338})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0xa4c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400029bd70, {0x1053c8098, 0x14000243940}, 0x14000684370)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xedc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140003d0820, {0x1053c8140, 0x1400027c1b0}, 0x1400061c000)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105366e40, 0x140003d0820}, {0x1053c8140, 0x1400027c1b0}, 0x1400007c540, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002acc40, {0x1053d6f58, 0x14000082820}, 0x14000618000, 0x140003f6a80, 0x1058ecbe0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xc5c
google.golang.org/grpc.(*Server).handleStream(0x140002acc40, {0x1053d6f58, 0x14000082820}, 0x14000618000, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000094550, 0x140002acc40, {0x1053d6f58, 0x14000082820}, 0x14000618000)
	google.golang.org/grpc@v1.45.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x1f0

Error: The terraform-provider-looker_v0.8.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by hirosassa** [comment]
@felipe-itoc Thanks for informing me! I'll take a look immediately.

**Comment by hirosassa** [comment]
@felipe-itoc I released v0.8.4 for this bug fix. Please try. And thanks again for your information!

Not related to the bug you informed, I haven't tried this provider on snowflake (I have no environment for it).
Please let me know if you notice anything!

**Comment by felipe-itoc** [comment]
Hi @hirosassa , thanks for the quick response.

I tested the new release and it works well for the `looker_connection` resource but I am still seeing errors for the `looker_user_attribute_group_value`.

```
Error: The terraform-provider-looker_v0.8.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Stack trace:**
```
Stack trace from the terraform-provider-looker_v0.8.4 plugin:

panic: interface conversion: interface {} is int, not string

goroutine 132 [running]:
github.com/hirosassa/terraform-provider-looker/pkg/looker.resourceUserAttributeGroupValueCreate({0x105710108, 0x14000489aa0}, 0x14000466a00, {0x1056eb960, 0x1400000e500})
	github.com/hirosassa/terraform-provider-looker/pkg/looker/resource_user_attribute_group_value.go:42 +0x44c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400021b0a0, {0x105710140, 0x140002bd9b0}, 0x14000466a00, {0x1056eb960, 0x1400000e500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400021b0a0, {0x105710140, 0x140002bd9b0}, 0x140003fb860, 0x14000466880, {0x1056eb960, 0x1400000e500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0xa4c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000205d88, {0x105710098, 0x140001c26c0}, 0x140006d0e60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xedc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140003d0820, {0x105710140, 0x140002bd320}, 0x14000148e70)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1056aee40, 0x140003d0820}, {0x105710140, 0x140002bd320}, 0x140004890e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400022cc40, {0x10571ef58, 0x1400050a1a0}, 0x1400046b7a0, 0x140003f6a80, 0x105c34be0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xc5c
google.golang.org/grpc.(*Server).handleStream(0x1400022cc40, {0x10571ef58, 0x1400050a1a0}, 0x1400046b7a0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400051a520, 0x1400022cc40, {0x10571ef58, 0x1400050a1a0}, 0x1400046b7a0)
	google.golang.org/grpc@v1.45.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x1f0
panic: interface conversion: interface {} is int, not string
```

Could you please have another look?

**Comment by hirosassa** [comment]
@felipe-itoc Sorry, this fixed in following issue.

https://github.com/hirosassa/terraform-provider-looker/issues/23
